import {
  // Original Outline Icons
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconMessageCircle,
  IconBrandGithub,
  IconFilePlus,
  IconBriefcase,
  IconClock,
  IconRefresh,

  // NEW: Corresponding Filled/Solid Icons for Active State
  IconLayoutDashboardFilled,
  IconCirclePlusFilled,
  IconFileTextFilled,
  IconBriefcaseFilled,
  IconCreditCardFilled,
  IconClockFilled,
  IconMessageCircleFilled,
  IconUserFilled, // CORRECTED: The solid version for a user icon
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // --- Original Outline Icons ---
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  connect: IconMessageCircle,
  proposals: IconFileText,
  request: IconFilePlus,
  engagements: IconBriefcase,
  history: IconClock,
  payments: IconCreditCard,
  refresh: IconRefresh,

  // --- NEW: Filled Icons for Active Sidebar State ---
  // These keys should match the `activeIcon` property in your `navItems` data
  dashboardFilled: IconLayoutDashboardFilled,
  requestFilled: IconCirclePlusFilled,
  proposalsFilled: IconFileTextFilled,
  engagementsFilled: IconBriefcaseFilled,
  paymentsFilled: IconCreditCardFilled,
  historyFilled: IconClockFilled,
  connectFilled: IconMessageCircleFilled,
  user2Filled: IconUserFilled, // CORRECTED: Mapped to the correct component
};